import { Share2, Sparkles } from 'lucide-react';

interface Insight {
  insight_text: string;
  source_metrics?: string[];
  confidence?: number;
  insight_type?: string;
}

interface InsightCapsuleProps {
  capsule: {
    capsule_date: string;
    personality_label: string;
    behavioral_insights: Insight[];
    trend_explanation: string;
    shareable_summary: string;
    generation_method: string;
    confidence_score?: number;
  };
}

export function InsightCapsule({ capsule }: InsightCapsuleProps) {
  const handleShare = () => {
    const text = `🎵 ${capsule.personality_label}\n\n${capsule.shareable_summary}\n\nGenerated by CapsuleOS`;
    if (navigator.share) {
      navigator.share({
        title: 'My Music Insight',
        text: text,
      });
    } else {
      navigator.clipboard.writeText(text);
      alert('Copied to clipboard!');
    }
  };

  return (
    <div className="bg-gradient-to-br from-slate-700/50 to-slate-800/50 border border-slate-600 rounded-xl p-8 backdrop-blur-sm">
      <div className="flex items-start justify-between mb-8">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-5 h-5 text-cyan-400" />
            <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
              {capsule.generation_method === 'llm' ? 'AI Generated' : 'Template'}
            </span>
          </div>
          <h2 className="text-4xl font-bold text-white mb-2">
            {capsule.personality_label}
          </h2>
          <p className="text-gray-400 text-sm">
            {new Date(capsule.capsule_date).toLocaleDateString('en-US', {
              weekday: 'long',
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })}
          </p>
        </div>
        <button
          onClick={handleShare}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-lg transition"
        >
          <Share2 className="w-4 h-4" />
          Share
        </button>
      </div>

      <div className="bg-slate-600/30 rounded-lg p-6 mb-8 border border-slate-600/50">
        <p className="text-gray-200 text-lg italic">
          "{capsule.shareable_summary}"
        </p>
      </div>

      {capsule.behavioral_insights && capsule.behavioral_insights.length > 0 && (
        <div className="mb-8">
          <h3 className="text-lg font-semibold text-white mb-4">Today's Insights</h3>
          <div className="space-y-3">
            {capsule.behavioral_insights.map((insight, idx) => (
              <div
                key={idx}
                className="bg-slate-600/20 border border-slate-600/30 rounded-lg p-4 flex gap-3"
              >
                <div className="w-8 h-8 flex-shrink-0 bg-blue-500/20 rounded-full flex items-center justify-center">
                  <span className="text-blue-300 font-bold text-sm">{idx + 1}</span>
                </div>
                <div className="flex-1">
                  <p className="text-gray-200">{insight.insight_text}</p>
                  {insight.confidence && (
                    <p className="text-gray-500 text-xs mt-2">
                      {(insight.confidence * 100).toFixed(0)}% confidence
                    </p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {capsule.trend_explanation && (
        <div className="bg-gradient-to-r from-slate-600/20 to-slate-700/20 border border-slate-600/30 rounded-lg p-6">
          <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">
            Trend
          </h3>
          <p className="text-gray-200">{capsule.trend_explanation}</p>
        </div>
      )}

      {capsule.confidence_score && (
        <div className="mt-8 pt-6 border-t border-slate-600/30 flex items-center justify-between">
          <p className="text-gray-500 text-xs">Overall confidence</p>
          <div className="flex items-center gap-2">
            <div className="w-24 h-2 bg-slate-600/30 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-blue-500 to-cyan-500 rounded-full transition-all"
                style={{ width: `${(capsule.confidence_score || 0) * 100}%` }}
              />
            </div>
            <span className="text-xs font-semibold text-gray-400">
              {(capsule.confidence_score * 100).toFixed(0)}%
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
